### PR TITLE
Add readOnly mode to PianoRoll

### PR DESCRIPTION
**Pull request by josephktcheung**
This PR adds `readOnly` mode to `PianoRoll`, which disable adding / editing / removing any note.
User can change black vertical line's opacity using PianoRoll's `noteLineOpacity`.

simulator_screenshot_1B435FBF-3550-4F79-A9A4-DFBAFFA4ED2C

### CODE REVIEW

**Comment by josephktcheung** [comment]
@aure @wtholliday please review thanks

**Review by wtholliday — CHANGES_REQUESTED** [review]
Please make the line opacity a setting instead of a function of `readOnly`.

**Comment by aure** [comment]
> Please make the line opacity a setting instead of a function of `readOnly`.

I agree that readOnly seems to be an implementation detail. Someone else might readonly to do something quite different to the UI.

**Comment by aure** [comment]
I'm sorry I think there's some confusion about variable naming and you were actually closer before the addition of note line opacity. I think removing the "handle" when you can't edit is an okay side effect. But I don't like the term "readOnly" for a boolean. I'd prefer "isEditable" or "editable" and its also a positive relationship can the user do something rather than can the user not do something.

**Comment by josephktcheung** [comment]
> I'm sorry I think there's some confusion about variable naming and you were actually closer before the addition of note line opacity. I think removing the "handle" when you can't edit is an okay side effect. But I don't like the term "readOnly" for a boolean. I'd prefer "isEditable" or "editable" and its also a positive relationship can the user do something rather than can the user not do something.

Renamed `readOnly` to `editable`, please take a look again.

**Pull request merged**
